### ISSUE TITLE
Issue after installing PyCALI

### ISSUE THREAD

**Issue by Shivangi1010** [LiyrAstroph/pyCALI#1]
Hi, 
I am encountering this issue while importing the pycali.
"ImportError: /home/shivangi/.local/lib/python3.8/site-packages/pycali-0.1.0-py3.8-linux-x86_64.egg/pycali/pycali.cpython-38-x86_64-linux-gnu.so: undefined symbol: _Z10cblas_ddotiPKdiS0_i"

Note: /home/shivangi/.local/lib/python3.8/site-packages/pycali-0.1.0-py3.8-linux-x86_64.egg/pycali/ is the path

**Comment by liyropt** [comment]
The error arises because the function "cblas_ddot" can not be found, usually occurring when the library CLBAS was not successfully installed or installed to a path not added to the system's  library path.
So please check the installation of CBLAS: whether there is a library "libcblas.so" in your system's library path (such as /usr/lib64). If not, add the path to "libcblas.so" to your system's library path as 

export LD_LIBRARY_PATH=/path/to/libcblas:$LD_LIBRARY_PATH

As such, the libcblas library and its function "cblas_ddot" can be found.

**Comment by Shivangi1010** [comment]
Thank you for your reply.
Although now I am getting attribute error: 
AttributeError: module 'pycali' has no attribute 'Config'
Is it because of the mismatch of some library or package version?

**Comment by Shivangi1010** [comment]
By libcblas.so, you mean libblas.so?
I did check and added the path. However, I am still encountering the error.
Can you suggest any other solution?

**Comment by Shivangi1010** [comment]
Also, can you tell me which Python version is suitable for it?
Python3.6+?

**Comment by liyropt** [comment]
If you using ubuntu,  "libblas.so" wraps all the functions of cblas. 
I am using Fedora Linux with Python 3.10, the installation works correctly.   Python3.9 also works. Not sure about earlier Python version.

The error seems related with CBLAS library. Make a try by replacing the following line in "setup.py"

libraries = ['m', 'c', 'gsl', 'gslcblas', 'lapack', 'lapacke']

with 

libraries = ['m', 'c', 'gsl', 'gslcblas', 'lapack', 'lapacke','blas']

This explicitly add the libblas library in linking. 

If this still does not work, please let me know. I will add a function to directly compile the source code of CBLAS and update setup.py.

**Comment by Shivangi1010** [comment]
This works!
Thanks a lot!

**Comment by liyropt** [comment]
Great! I submitted an update to setup.py accordingly.
Thanks for reporting the error.
